2023-12-27 13:57:40,896 INFO    StreamThr :12272 [internal.py:wandb_internal():86] W&B internal server running at pid: 12272, started at: 2023-12-27 13:57:40.895725
2023-12-27 13:57:40,900 DEBUG   HandlerThread:12272 [handler.py:handle_request():146] handle_request: status
2023-12-27 13:57:40,902 INFO    WriterThread:12272 [datastore.py:open_for_write():85] open: D:\Projects\Data Science\machine_translation\wandb\run-20231227_135740-jua11bll\run-jua11bll.wandb
2023-12-27 13:57:40,905 DEBUG   SenderThread:12272 [sender.py:send():382] send: header
2023-12-27 13:57:40,956 DEBUG   SenderThread:12272 [sender.py:send():382] send: run
2023-12-27 13:57:42,035 INFO    SenderThread:12272 [dir_watcher.py:__init__():211] watching files in: D:\Projects\Data Science\machine_translation\wandb\run-20231227_135740-jua11bll\files
2023-12-27 13:57:42,035 INFO    SenderThread:12272 [sender.py:_start_run_threads():1136] run started: jua11bll with start time 1703665660.896725
2023-12-27 13:57:42,046 DEBUG   HandlerThread:12272 [handler.py:handle_request():146] handle_request: check_version
2023-12-27 13:57:42,046 DEBUG   SenderThread:12272 [sender.py:send_request():409] send_request: check_version
2023-12-27 13:57:42,577 DEBUG   HandlerThread:12272 [handler.py:handle_request():146] handle_request: run_start
2023-12-27 13:57:42,711 DEBUG   HandlerThread:12272 [system_info.py:__init__():32] System info init
2023-12-27 13:57:42,711 DEBUG   HandlerThread:12272 [system_info.py:__init__():47] System info init done
2023-12-27 13:57:42,711 INFO    HandlerThread:12272 [system_monitor.py:start():194] Starting system monitor
2023-12-27 13:57:42,712 INFO    SystemMonitor:12272 [system_monitor.py:_start():158] Starting system asset monitoring threads
2023-12-27 13:57:42,712 INFO    HandlerThread:12272 [system_monitor.py:probe():214] Collecting system info
2023-12-27 13:57:42,715 INFO    SystemMonitor:12272 [interfaces.py:start():190] Started cpu monitoring
2023-12-27 13:57:42,717 INFO    SystemMonitor:12272 [interfaces.py:start():190] Started disk monitoring
2023-12-27 13:57:42,718 INFO    SystemMonitor:12272 [interfaces.py:start():190] Started gpu monitoring
2023-12-27 13:57:42,719 INFO    SystemMonitor:12272 [interfaces.py:start():190] Started memory monitoring
2023-12-27 13:57:42,729 INFO    SystemMonitor:12272 [interfaces.py:start():190] Started network monitoring
2023-12-27 13:57:42,738 DEBUG   HandlerThread:12272 [system_info.py:probe():196] Probing system
2023-12-27 13:57:42,739 ERROR   gpu       :12272 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-27 13:57:42,740 DEBUG   HandlerThread:12272 [system_info.py:_probe_git():181] Probing git
2023-12-27 13:57:42,740 ERROR   gpu       :12272 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-27 13:57:42,848 DEBUG   HandlerThread:12272 [system_info.py:_probe_git():189] Probing git done
2023-12-27 13:57:42,849 DEBUG   HandlerThread:12272 [system_info.py:probe():244] Probing system done
2023-12-27 13:57:42,849 DEBUG   HandlerThread:12272 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.10.13', 'heartbeatAt': '2023-12-27T08:27:42.738772', 'startedAt': '2023-12-27T08:27:40.875659', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'd:\\Projects\\Data Science\\machine_translation\\train_transformer.py', 'codePathLocal': 'train_transformer.py', 'codePath': 'train_transformer.py', 'git': {'remote': 'https://github.com/svarunid/machine-translation.git', 'commit': 'b7e5d346fd54ddc97370f818fb0830432d0c78b2'}, 'email': 'svarunid@gmail.com', 'root': 'D:/Projects/Data Science/machine_translation', 'host': 'Dhev', 'username': 'Arun', 'executable': 'D:\\Projects\\Data Science\\env\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 1792.0, 'min': 0.0, 'max': 1992.0}, 'cpu_freq_per_core': [{'current': 1792.0, 'min': 0.0, 'max': 1992.0}], 'disk': {'/': {'total': 146.48437118530273, 'used': 56.00380325317383}}, 'gpu': 'NVIDIA GeForce MX250', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce MX250', 'memory_total': 2147483648}], 'memory': {'total': 15.816089630126953}}
2023-12-27 13:57:42,849 INFO    HandlerThread:12272 [system_monitor.py:probe():224] Finished collecting system info
2023-12-27 13:57:42,849 INFO    HandlerThread:12272 [system_monitor.py:probe():227] Publishing system info
2023-12-27 13:57:42,849 DEBUG   HandlerThread:12272 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-12-27 13:57:42,850 DEBUG   HandlerThread:12272 [system_info.py:_save_pip():68] Saving pip packages done
2023-12-27 13:57:42,850 DEBUG   HandlerThread:12272 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-12-27 13:57:42,853 ERROR   HandlerThread:12272 [system_info.py:_save_conda():86] Error saving conda packages: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\Projects\Data Science\env\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    subprocess.call(
  File "D:\Projects\Data Science\env\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Projects\Data Science\env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Projects\Data Science\env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-12-27 13:57:42,879 DEBUG   HandlerThread:12272 [system_info.py:_save_conda():87] Saving conda packages done
2023-12-27 13:57:42,880 INFO    HandlerThread:12272 [system_monitor.py:probe():229] Finished publishing system info
2023-12-27 13:57:42,888 DEBUG   SenderThread:12272 [sender.py:send():382] send: files
2023-12-27 13:57:42,889 INFO    SenderThread:12272 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2023-12-27 13:57:42,902 DEBUG   HandlerThread:12272 [handler.py:handle_request():146] handle_request: stop_status
2023-12-27 13:57:42,906 DEBUG   SenderThread:12272 [sender.py:send_request():409] send_request: stop_status
2023-12-27 13:57:42,906 DEBUG   HandlerThread:12272 [handler.py:handle_request():146] handle_request: internal_messages
2023-12-27 13:57:43,045 INFO    Thread-16 :12272 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Projects\Data Science\machine_translation\wandb\run-20231227_135740-jua11bll\files\requirements.txt
2023-12-27 13:57:43,045 INFO    Thread-16 :12272 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Projects\Data Science\machine_translation\wandb\run-20231227_135740-jua11bll\files\conda-environment.yaml
2023-12-27 13:57:43,045 INFO    Thread-16 :12272 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Projects\Data Science\machine_translation\wandb\run-20231227_135740-jua11bll\files\wandb-metadata.json
2023-12-27 13:57:43,810 DEBUG   SenderThread:12272 [sender.py:send():382] send: telemetry
2023-12-27 13:57:44,055 INFO    Thread-16 :12272 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Projects\Data Science\machine_translation\wandb\run-20231227_135740-jua11bll\files\output.log
2023-12-27 13:57:44,486 INFO    wandb-upload_0:12272 [upload_job.py:push():131] Uploaded file C:\Users\Arun\AppData\Local\Temp\tmps1bp_j9ewandb\l6agxkm8-wandb-metadata.json
2023-12-27 13:57:44,771 ERROR   gpu       :12272 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-27 13:57:44,771 ERROR   gpu       :12272 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-27 13:57:46,072 INFO    Thread-16 :12272 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Projects\Data Science\machine_translation\wandb\run-20231227_135740-jua11bll\files\output.log
2023-12-27 13:57:46,728 INFO    cpu       :12272 [interfaces.py:monitor():140] Process cpu has exited.
2023-12-27 13:57:46,729 DEBUG   SystemMonitor:12272 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2023-12-27 13:57:46,730 ERROR   gpu       :12272 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-12-27 13:57:46,730 DEBUG   SystemMonitor:12272 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2023-12-27 13:57:46,730 DEBUG   SystemMonitor:12272 [system_monitor.py:_start():183] Publishing last batch of metrics
2023-12-27 13:57:46,732 DEBUG   SenderThread:12272 [sender.py:send():382] send: stats
2023-12-27 13:57:46,733 DEBUG   HandlerThread:12272 [handler.py:handle_request():146] handle_request: status_report
2023-12-27 13:57:47,633 INFO    MainThread:12272 [internal.py:handle_exit():76] Internal process exited
